import 'package:flutter/material.dart';

Map<String, Color> pokemonTypeColors = {
  "normal": Colors.grey,
  "fighting": Colors.red,
  "flying": Colors.blue[400]!,
  "poison": Colors.purple,
  "ground": Colors.brown,
  "rock": Colors.grey[800]!,
  "bug": Colors.green,
  "ghost": Colors.indigo,
  "steel": Colors.blueGrey,
  "fire": Colors.orange,
  "water": Colors.blue,
  "grass": Colors.green[700]!,
  "electric": Colors.yellow,
  "psychic": Colors.pink,
  "ice": Colors.cyan,
  "dragon": Colors.redAccent,
  "dark": Colors.black,
  "fairy": Colors.pinkAccent,
  "stellar": Colors.amber,
  "unknown": Colors.transparent,
  "shadow": Colors.black87,
};
